name: bacnet
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # PyTorch + CUDA
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8

  # Conda packages
  - rdkit
  - pandas
  - numpy
  - matplotlib
  - reportlab
  - pyarrow
  - tqdm
  - transformers
  - "setuptools<81"

  # Pip-only package(s)
  - pip:
      - signaturizer